/**
 * Workspace projection (spec §12): write team-shareable memories to
 * `<workspace>/.repo_memory/` so they can be reviewed, committed, and shared
 * through the repository itself.
 *
 * Three gates, in this order — each one closes a different failure:
 *   1. **whitelist**: only `visibility = 'team-shareable'` rows project. That
 *      visibility has exactly one writer: an approved promotion (below).
 *   2. **human approval**: promotion goes through the platform's approval
 *      service, so a model can never publish on its own. `human_confirmed`
 *      records that a person said yes.
 *   3. **secret scan**: the last line of defence, applied to the rendered
 *      text at write time — a memory that looks like it carries a credential
 *      is skipped even if approved, because approval is about intent and
 *      this is about accident.
 *
 * The file is a pure projection: deleted and rewritten from the store, never
 * read back. Nothing here can become an input — a checked-in file editable by
 * anyone must not be able to inject memories (D1).
 * @module @strataloom/dsh-memory/projection
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { OpenStore } from './store/store.ts'
import type { MemoryHit } from './types.ts'

/** Directory written under the workspace root. */
export const PROJECTION_DIR = '.repo_memory'
/** The single projected file. */
export const PROJECTION_FILE = 'memories.md'

/**
 * Patterns that look like credentials. Deliberately broad: a false positive
 * costs one unshared memory, a false negative commits a secret to a repo.
 */
const SECRET_PATTERNS: readonly RegExp[] = [
  /\b(?:sk|pk|ghp|gho|ghu|ghs|ghr|xox[baprs])[-_][A-Za-z0-9_-]{16,}/i,
  /\bAKIA[0-9A-Z]{16}\b/,
  /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\./,
  /-----BEGIN[ A-Z]*PRIVATE KEY-----/,
  /\b(?:password|passwd|secret|api[_-]?key|access[_-]?token|client[_-]?secret)\s*[:=]\s*\S{6,}/i,
  /\b[a-f0-9]{40,}\b/i, // long hex blobs: tokens, hashes of unclear origin
]

/** Whether text looks like it carries a credential. */
export const looksSecret = (text: string): boolean =>
  SECRET_PATTERNS.some((pattern) => pattern.test(text))

const render = (rows: readonly MemoryHit[]): string => {
  const lines = [
    '<!-- Generated by @strataloom/dsh-memory. Edits are overwritten and are',
    '     never read back into memory. Manage entries with the memory tools. -->',
    '',
    '# Repository memory',
    '',
  ]
  for (const row of rows) {
    lines.push(`## ${row.title}`, '', `- kind: ${row.kind}`, '', row.body, '')
  }
  return lines.join('\n')
}

/**
 * Rewrite the projection from the store's approved, team-shareable rows.
 * Removes the directory when nothing qualifies, so revoking the last shared
 * memory leaves no stale file behind.
 */
export const projectStore = (store: OpenStore, workspaceDir: string) => {
  const rows = store.db
    .prepare(
      `SELECT id, kind, title, body FROM memories
       WHERE visibility = 'team-shareable' AND human_confirmed = 1
         AND status = 'active' AND derived = 0
       ORDER BY updated_at DESC`,
    )
    .all() as unknown as MemoryHit[]

  const safe = rows.filter((row) => !looksSecret(`${row.title}\n${row.body}`))
  const dir = join(workspaceDir, PROJECTION_DIR)
  const path = join(dir, PROJECTION_FILE)

  if (safe.length === 0) {
    rmSync(dir, { recursive: true, force: true })
    return { written: 0, skippedSecrets: rows.length - safe.length, path }
  }
  mkdirSync(dir, { recursive: true })
  writeFileSync(path, render(safe), 'utf8')
  return { written: safe.length, skippedSecrets: rows.length - safe.length, path }
}
