/**
 * Workspace projection (spec §12): write team-shareable memories to
 * `<workspace>/.repo_memory/` so they can be reviewed, committed, and shared
 * through the repository itself.
 *
 * Three gates, in this order — each one closes a different failure:
 *   1. **whitelist**: only `visibility = 'team-shareable'` rows project. That
 *      visibility has exactly one writer: an approved promotion (below).
 *   2. **human approval**: promotion goes through the platform's approval
 *      service, so a model can never publish on its own. `human_confirmed`
 *      records that a person said yes.
 *   3. **secret scan**: the last line of defence, applied to the rendered
 *      text at write time — a memory that looks like it carries a credential
 *      is skipped even if approved, because approval is about intent and
 *      this is about accident.
 *
 * The file is a pure projection: deleted and rewritten from the store, never
 * read back. Nothing here can become an input — a checked-in file editable by
 * anyone must not be able to inject memories (D1).
 * @module @strataloom/dsh-memory/projection
 */
import { existsSync, mkdirSync, readdirSync, rmdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { OpenStore } from './store/store.ts'
import type { MemoryHit } from './types.ts'

/** Directory written under the workspace root. */
export const PROJECTION_DIR = '.repo_memory'
/** The single projected file. */
export const PROJECTION_FILE = 'memories.md'

/**
 * Patterns that look like credentials. Deliberately broad: a false positive
 * costs one unshared memory, a false negative commits a secret to a repo.
 */
const SECRET_PATTERNS: readonly RegExp[] = [
  /\b(?:sk|pk|ghp|gho|ghu|ghs|ghr|xox[baprs])[-_][A-Za-z0-9_-]{16,}/i,
  /\bAKIA[0-9A-Z]{16}\b/,
  /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\./,
  /-----BEGIN[ A-Z]*PRIVATE KEY-----/,
  /\b(?:password|passwd|secret|api[_-]?key|access[_-]?token|client[_-]?secret)\s*[:=]\s*\S{6,}/i,
  /\b[a-f0-9]{40,}\b/i, // long hex blobs: tokens, hashes of unclear origin
]

/** Whether text looks like it carries a credential. */
export const looksSecret = (text: string): boolean =>
  SECRET_PATTERNS.some((pattern) => pattern.test(text))

const render = (rows: readonly MemoryHit[]): string => {
  const lines = [
    '<!-- Generated by @strataloom/dsh-memory. Edits are overwritten and are',
    '     never read back into memory. Manage entries with the memory tools. -->',
    '',
    '# Repository memory',
    '',
  ]
  for (const row of rows) {
    lines.push(`## ${row.title}`, '', `- kind: ${row.kind}`, '', row.body, '')
  }
  return lines.join('\n')
}

/**
 * Rewrite the projection from the store's approved, team-shareable rows.
 * Removes ONLY the projected file when nothing qualifies, so revoking the last
 * shared memory leaves no stale file behind; the directory itself is removed
 * only if that leaves it empty.
 *
 * It used to say "removes the directory when nothing qualifies" and it meant
 * it literally: `rmSync(dir, { recursive: true })`.
 *
 * ORIGINAL JUSTIFICATION, KEPT AND MARKED REFUTED (house rule: a judgement
 * that turned out wrong is annotated, not quietly rewritten). This comment
 * argued the recursive delete had been safe only because the zero-row branch
 * was DEAD — `share` being the sole caller, pre-scanning with `looksSecret`
 * before promoting the row, so `safe.length >= 1` always held — and concluded
 * that `refreshProjection`, via `forget`, was "the first caller that can
 * genuinely reach zero rows". That is FALSE, and the reasoning error was
 * stepping over an `await`: `share` suspends between its status check and its
 * UPDATE to ask a human for approval, that UPDATE carries `AND status =
 * 'active'`, and `runDecayJob` runs concurrently off `ctx.interval` putting
 * idle rows to sleep. Reproduced on UNMODIFIED HEAD through the production
 * writer path (`enqueueJob` / `claimNextJob` / `runDecayJob`) with one decay
 * pass inside the approval window: the UPDATE matched nothing, this SELECT
 * returned zero rows, `share` reported "0 memory/memories", and the recursive
 * delete erased a checked-in `.repo_memory/` down to a hand-written
 * `NOTES.md`.
 *
 * So narrowing the delete is not prevention of a risk this module was about
 * to introduce — it REPAIRS A DEFECT HEAD CAN ALREADY REACH. `.repo_memory/`
 * is a CHECKED-IN directory: a team may keep `NOTES.md`, a `README.md`, or
 * whole subtrees beside the generated file, and recursively deleting it
 * destroys hand-written, version-controlled work this module never wrote.
 *
 * FAILURES ARE NOT HANDLED HERE, deliberately. This function may throw — a
 * `memories.md` that is a DIRECTORY makes `rmSync` raise EISDIR, which
 * `force: true` does not suppress (it suppresses ENOENT only) — and
 * `MemoryService.refreshProjection` owns the single try/catch that decides
 * what a projection failure means. An earlier revision wrapped the directory
 * cleanup alone, leaving `rmSync`, `mkdirSync` and `writeFileSync` bare while
 * this comment already stated the right principle, "a forget must not fail
 * because tidying up did": the principle was correct and the implementation
 * honoured it for one call out of four. One rule, one place.
 */
export const projectStore = (store: OpenStore, workspaceDir: string) => {
  const rows = store.db
    .prepare(
      `SELECT id, kind, title, body FROM memories
       WHERE visibility = 'team-shareable' AND human_confirmed = 1
         AND status = 'active' AND derived = 0
       ORDER BY updated_at DESC`,
    )
    .all() as unknown as MemoryHit[]

  const safe = rows.filter((row) => !looksSecret(`${row.title}\n${row.body}`))
  const dir = join(workspaceDir, PROJECTION_DIR)
  const path = join(dir, PROJECTION_FILE)

  if (safe.length === 0) {
    // Delete what this module wrote, and nothing else.
    rmSync(path, { force: true })
    // Drop the directory only when removing our file left it empty, so a
    // team's own files keep it alive. Uncaught on purpose: see the note above
    // — the caller's single handler decides whether a projection failure is
    // fatal, and duplicating that judgement here is what made it half true.
    if (existsSync(dir) && readdirSync(dir).length === 0) rmdirSync(dir)
    return { written: 0, skippedSecrets: rows.length - safe.length, path }
  }
  mkdirSync(dir, { recursive: true })
  writeFileSync(path, render(safe), 'utf8')
  return { written: safe.length, skippedSecrets: rows.length - safe.length, path }
}
